version: '3.1'

services:

  postgres_db:
    container_name: postgres-dev
    image: postgres:12-alpine
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=demo
